# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenSelena.OmniGet
PackageVersion: 0.10.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: omniget
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayName: omniget
  ProductCode: omniget
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\omniget'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/OpenSelena/omniget/releases/download/v0.10.0/omniget_0.10.0_x64-setup.exe
  InstallerSha256: 0ECC6E27AB2711CB524319B7DF1CF15C22E8F4EC97A9DADCB00C517D80B1D83D
ManifestType: installer
ManifestVersion: 1.12.0
