# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: OpenSelena.OmniGet
PackageVersion: 0.10.0
PackageLocale: en-US
Publisher: OpenSelena
PublisherUrl: https://github.com/OpenSelena
PublisherSupportUrl: https://github.com/OpenSelena/omniget/issues
Author: OpenSelena
PackageName: OmniGet
PackageUrl: https://omniget.nav.bd/
License: GPL-3.0
LicenseUrl: https://github.com/OpenSelena/omniget/blob/main/LICENSE
ShortDescription: Desktop app to download videos, courses, and media from 1,800+ platforms.
Description: Desktop app to download videos, courses, and media from 1,800+ platforms. YouTube, Instagram, TikTok, Bilibili, Douyin, Hotmart, Udemy, Kiwify, Telegram, and 1000+ more via yt-dlp.
Tags:
- video-downloader
- course-downloader
- download-manager
- media-downloader
- rust
- tauri
- youtube-downloader
- yt-dlp
ReleaseNotesUrl: https://github.com/OpenSelena/omniget/releases/tag/v0.10.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
